# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Digaws < Formula
  desc "Look up region and other information for any AWS IP address"
  homepage "https://github.com/sampointer/digaws"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sampointer/digaws/releases/download/v0.2.0/digaws_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "0f9b3073d0c5156cf2e6c5dc1be45a3ee7e89c90e55a93e336e6bafa2195e05f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sampointer/digaws/releases/download/v0.2.0/digaws_0.2.0_Linux_x86_64.tar.gz"
    sha256 "bb6ed834fc58196c03d1b1252a560369ca89c149f9a497bbc52e577769a2f09e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sampointer/digaws/releases/download/v0.2.0/digaws_0.2.0_Linux_arm64.tar.gz"
    sha256 "33cf840ece99dd6bd3287b5396c96fa5d2b6e71bde1eba4cca52b727a5494781"
  end

  def install
    bin.install "digaws"
  end
end
